apiVersion: v1
kind: Service
metadata:
    name: my-deno-app-service
  labels:
    app: web
spec:
    type: NodePort
  ports:
  - ports: 80 
    targetPort: 80
    nodePort: 30020
selector: 
    app: web	